steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'backend/Dockerfile'
      - '-t'
      - '$_IMAGE'
      - '.'
    
  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_IMAGE'
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backend'
      - '--image'
      - '$_IMAGE'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '100'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '60'
      - '--concurrency'
      - '1000'
      - '--set-env-vars'
      - 'FIREBASE_PROJECT_ID=$_FIREBASE_PROJECT_ID,R2_ACCOUNT_ID=$_R2_ACCOUNT_ID,R2_BUCKET_NAME=$_R2_BUCKET_NAME'
      - '--set-secrets'
      - 'R2_ACCESS_KEY_ID=R2_ACCESS_KEY_ID:latest,R2_SECRET_ACCESS_KEY=R2_SECRET_ACCESS_KEY:latest'

substitutions:
  _REGION: 'asia-northeast3'
  _IMAGE: '${_REGION}-docker.pkg.dev/$PROJECT_ID/api/backend:$SHORT_SHA'
  _FIREBASE_PROJECT_ID: 'your-firebase-project'
  _R2_ACCOUNT_ID: 'your-r2-account'
  _R2_BUCKET_NAME: 'your-bucket-name'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'